DEATH_DATA_DIR <- file.path("death_data")
OPIOID_DEATH_DIR <- file.path(DEATH_DATA_DIR, "opioid_death_tables")
TEMPERATURE_DATA_DIR <- file.path("temperature_data")
MISC_DATA_DIR <- file.path("misc_data")
PLOT_DIR <- file.path("plots")
